server:
  port: 8099

camunda:
  bpm:
    admin-user:
      id: admin
      password: 123456
      first-name: laq
    filter:
      create: All tasks

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: 000000
    type: com.mysql.cj.jdbc.MysqlDataSource